"""Pydantic schemas package for request/response validation."""

from app.schemas.auth import LoginRequest, RegisterRequest, TokenResponse
from app.schemas.booking import (
    BookingBase,
    BookingCreate,
    BookingDetailResponse,
    BookingResponse,
    BookingStatusUpdate,
    BookingUpdate,
    RatingBase,
    RatingCreate,
    RatingResponse,
)
from app.schemas.service import (
    ServiceCategoryBase,
    ServiceCategoryCreate,
    ServiceCategoryResponse,
    ServiceCategoryUpdate,
    SkillBase,
    SkillCreate,
    SkillResponse,
)
from app.schemas.user import (
    CooperativeBase,
    CooperativeCreate,
    CooperativeResponse,
    CooperativeUpdate,
    CustomerBase,
    CustomerCreate,
    CustomerResponse,
    CustomerUpdate,
    UserBase,
    UserCreate,
    UserResponse,
    UserUpdate,
)
from app.schemas.worker import (
    CertificationBase,
    CertificationCreate,
    CertificationResponse,
    CertificationUpdate,
    WorkerAvailabilityUpdate,
    WorkerBase,
    WorkerCreate,
    WorkerDetailResponse,
    WorkerResponse,
    WorkerSkillBase,
    WorkerSkillCreate,
    WorkerSkillResponse,
    WorkerUpdate,
)

__all__ = [
    # Auth
    "LoginRequest",
    "RegisterRequest",
    "TokenResponse",
    # User / Customer / Cooperative
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "CustomerBase",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerResponse",
    "CooperativeBase",
    "CooperativeCreate",
    "CooperativeUpdate",
    "CooperativeResponse",
    # Worker
    "WorkerBase",
    "WorkerCreate",
    "WorkerUpdate",
    "WorkerResponse",
    "WorkerDetailResponse",
    "WorkerAvailabilityUpdate",
    "WorkerSkillBase",
    "WorkerSkillCreate",
    "WorkerSkillResponse",
    "CertificationBase",
    "CertificationCreate",
    "CertificationUpdate",
    "CertificationResponse",
    # Service
    "ServiceCategoryBase",
    "ServiceCategoryCreate",
    "ServiceCategoryUpdate",
    "ServiceCategoryResponse",
    "SkillBase",
    "SkillCreate",
    "SkillResponse",
    # Booking & Rating
    "BookingBase",
    "BookingCreate",
    "BookingUpdate",
    "BookingStatusUpdate",
    "BookingResponse",
    "BookingDetailResponse",
    "RatingBase",
    "RatingCreate",
    "RatingResponse",
]
